# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e3ae053c87cefc6f587cd38fa4e496801ff63906bd20e4765c319d8156c96808f0dbf1d22758ff6d6dbd8b4be92674a15b2e440d01e2e9e0e72750ca946df92

test:
  secret_key_base: a8da5517e5086fad48b8d6ad9f444d26cc79091e9074b0caa23cc80f02e179b8ecff5550cde9b69dd5f61b1413c0db6fa025695e4e90c39b8c61ec86046bc950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
